CREATE DATABASE QLTaiKhoan

USE QLTaiKhoan

CREATE TABLE DULIEUTAIKHOAN
(
	TENDANGNHAP VARCHAR(20) PRIMARY KEY ,
	MATKHAU	VARCHAR(20)
)
INSERT INTO DULIEUTAIKHOAN
(TENDANGNHAP,MATKHAU) VALUES ('USER1','1234');
INSERT INTO DULIEUTAIKHOAN
(TENDANGNHAP,MATKHAU) VALUES ('USER2','1234');
select * from DULIEUTAIKHOAN 
CREATE TABLE DANHSACHPHONG
(
	IDPHONG INT PRIMARY KEY,
	CHUPHONG VARCHAR(20),
	LOAIBAN VARCHAR(20),	
	MATKHAU VARCHAR(20),
	SONGUOI INT

)
INSERT INTO DANHSACHPHONG (IDPHONG, CHUPHONG, LOAIBAN, MATKHAU, SONGUOI)
VALUES ('1', 'ZIECTHANH', 'BinhDan', ' ', '2')
DROP TABLE DANHSACHPHONG
select * from DANHSACHPHONG